"""Add UI management models

Revision ID: 007dd95a58a0
Revises: 99d8de282dcb
Create Date: 2025-09-16 12:08:55.479972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '007dd95a58a0'
down_revision = '99d8de282dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_text', sa.String(length=200), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_suggestions'))
    )
    op.create_index(op.f('ix_search_suggestions_id'), 'search_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_search_suggestions_suggestion_text'), 'search_suggestions', ['suggestion_text'], unique=False)
    op.create_table('ui_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_key', sa.String(length=100), nullable=False),
    sa.Column('preference_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_user_configurable', sa.Boolean(), nullable=False),
    sa.Column('requires_admin', sa.Boolean(), nullable=False),
    sa.Column('affects_security', sa.Boolean(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('modified_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ui_preferences'))
    )
    op.create_index(op.f('ix_ui_preferences_id'), 'ui_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_ui_preferences_preference_key'), 'ui_preferences', ['preference_key'], unique=True)
    op.create_table('global_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('results_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_global_search_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_search'))
    )
    op.create_index(op.f('ix_global_search_id'), 'global_search', ['id'], unique=False)
    op.create_index(op.f('ix_global_search_search_id'), 'global_search', ['search_id'], unique=True)
    op.create_table('ui_bulk_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('target_model', sa.String(length=50), nullable=False),
    sa.Column('operation_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('successful_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('success_rate', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ui_bulk_operations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ui_bulk_operations'))
    )
    op.create_index(op.f('ix_ui_bulk_operations_id'), 'ui_bulk_operations', ['id'], unique=False)
    op.create_index(op.f('ix_ui_bulk_operations_operation_id'), 'ui_bulk_operations', ['operation_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Enum('LIGHT', 'DARK', 'SYSTEM', 'AUTO', name='themetype'), nullable=False),
    sa.Column('language', sa.Enum('ENGLISH', 'SWAHILI', 'FRENCH', 'SPANISH', name='languagecode'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('currency_display', sa.String(length=10), nullable=False),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('default_page', sa.String(length=50), nullable=False),
    sa.Column('sidebar_collapsed', sa.Boolean(), nullable=False),
    sa.Column('show_tooltips', sa.Boolean(), nullable=False),
    sa.Column('default_page_size', sa.Integer(), nullable=False),
    sa.Column('show_row_numbers', sa.Boolean(), nullable=False),
    sa.Column('enable_auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('auto_refresh_interval', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Enum('ALL', 'IMPORTANT', 'NONE', name='notificationpreference'), nullable=False),
    sa.Column('sms_notifications', sa.Enum('ALL', 'IMPORTANT', 'NONE', name='notificationpreference'), nullable=False),
    sa.Column('browser_notifications', sa.Enum('ALL', 'IMPORTANT', 'NONE', name='notificationpreference'), nullable=False),
    sa.Column('notification_sound', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_method', sa.String(length=20), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('require_password_on_sensitive', sa.Boolean(), nullable=False),
    sa.Column('saved_searches', sa.JSON(), nullable=True),
    sa.Column('search_history', sa.JSON(), nullable=True),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('quick_filters', sa.JSON(), nullable=True),
    sa.Column('bulk_operation_confirmation', sa.Boolean(), nullable=False),
    sa.Column('max_bulk_operations', sa.Integer(), nullable=False),
    sa.Column('bulk_operation_timeout', sa.Integer(), nullable=False),
    sa.Column('developer_mode', sa.Boolean(), nullable=False),
    sa.Column('show_debug_info', sa.Boolean(), nullable=False),
    sa.Column('enable_keyboard_shortcuts', sa.Boolean(), nullable=False),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_key'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_type', postgresql.ENUM('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'ENCRYPTED', name='configtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    op.create_index(op.f('ix_configurations_key'), 'configurations', ['key'], unique=True)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_ui_bulk_operations_operation_id'), table_name='ui_bulk_operations')
    op.drop_index(op.f('ix_ui_bulk_operations_id'), table_name='ui_bulk_operations')
    op.drop_table('ui_bulk_operations')
    op.drop_index(op.f('ix_global_search_search_id'), table_name='global_search')
    op.drop_index(op.f('ix_global_search_id'), table_name='global_search')
    op.drop_table('global_search')
    op.drop_index(op.f('ix_ui_preferences_preference_key'), table_name='ui_preferences')
    op.drop_index(op.f('ix_ui_preferences_id'), table_name='ui_preferences')
    op.drop_table('ui_preferences')
    op.drop_index(op.f('ix_search_suggestions_suggestion_text'), table_name='search_suggestions')
    op.drop_index(op.f('ix_search_suggestions_id'), table_name='search_suggestions')
    op.drop_table('search_suggestions')
    # ### end Alembic commands ###
