"""Add configuration version tracking to provisioning models

Revision ID: 092bd52af6a2
Revises: 279ffe74982f
Create Date: 2026-01-27 19:05:08.708310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092bd52af6a2'
down_revision = '279ffe74982f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provisioning_sessions', sa.Column('configuration_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('provisioning_sessions', sa.Column('previous_configuration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_provisioning_sessions_previous_configuration_id_router_configurations'), 'provisioning_sessions', 'router_configurations', ['previous_configuration_id'], ['id'])
    op.add_column('router_configurations', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('routers', 'provisioning_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('routers', 'bootstrap_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_routers_provisioning_status'), table_name='routers', if_exists=True)
    
    # Add service_plans columns with default values first, then alter to remove defaults
    op.add_column('service_plans', sa.Column('is_template', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('service_plans', sa.Column('template_category', sa.String(length=50), nullable=True))
    op.add_column('service_plans', sa.Column('enable_burst', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('service_plans', sa.Column('burst_download', sa.Integer(), nullable=True))
    op.add_column('service_plans', sa.Column('burst_upload', sa.Integer(), nullable=True))
    op.add_column('service_plans', sa.Column('burst_threshold', sa.Integer(), nullable=True))
    op.add_column('service_plans', sa.Column('burst_time', sa.Integer(), nullable=True))
    op.add_column('service_plans', sa.Column('enable_schedule', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('service_plans', sa.Column('schedule_start_time', sa.String(length=5), nullable=True))
    op.add_column('service_plans', sa.Column('schedule_end_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_plans', 'schedule_end_time')
    op.drop_column('service_plans', 'schedule_start_time')
    op.drop_column('service_plans', 'enable_schedule')
    op.drop_column('service_plans', 'burst_time')
    op.drop_column('service_plans', 'burst_threshold')
    op.drop_column('service_plans', 'burst_upload')
    op.drop_column('service_plans', 'burst_download')
    op.drop_column('service_plans', 'enable_burst')
    op.drop_column('service_plans', 'template_category')
    op.drop_column('service_plans', 'is_template')
    op.create_index(op.f('idx_routers_provisioning_status'), 'routers', ['provisioning_status'], unique=False)
    op.alter_column('routers', 'bootstrap_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('routers', 'provisioning_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('router_configurations', 'version')
    op.drop_constraint(op.f('fk_provisioning_sessions_previous_configuration_id_router_configurations'), 'provisioning_sessions', type_='foreignkey')
    op.drop_column('provisioning_sessions', 'previous_configuration_id')
    op.drop_column('provisioning_sessions', 'configuration_version')
    # ### end Alembic commands ###
