"""Fix model relationships and foreign keys

Revision ID: 3aae684d6ae6
Revises: 007dd95a58a0
Create Date: 2025-09-16 12:31:17.001591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3aae684d6ae6'
down_revision = '007dd95a58a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_key'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_type', postgresql.ENUM('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'ENCRYPTED', name='configtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    op.create_index(op.f('ix_configurations_key'), 'configurations', ['key'], unique=True)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    # ### end Alembic commands ###
