"""add_licence_enforcement_columns_to_organizations

Revision ID: 4a2822ac5c07
Revises: a2f8c94d1e3b
Create Date: 2026-02-08 18:55:31.855053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2822ac5c07'
down_revision = 'a2f8c94d1e3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('grace_period_days', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('organizations', sa.Column('grace_period_ends_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('licence_bypass', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organizations', sa.Column('bypass_reason', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('bypass_set_by', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_organizations_bypass_set_by_users'), 'organizations', 'users', ['bypass_set_by'], ['id'])
    op.add_column('platform_whatsapp_settings', sa.Column('minimum_subscription_months', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('platform_whatsapp_settings', sa.Column('payment_method', sa.String(length=50), nullable=False, server_default='mpesa'))
    op.add_column('platform_whatsapp_settings', sa.Column('mpesa_paybill', sa.String(length=20), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('mpesa_till_number', sa.String(length=20), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('mpesa_account_name', sa.String(length=100), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('bank_account_number', sa.String(length=50), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('bank_branch', sa.String(length=100), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('bank_swift_code', sa.String(length=20), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('paystack_subaccount_code', sa.String(length=100), nullable=True))
    op.add_column('platform_whatsapp_settings', sa.Column('auto_renewal_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('platform_whatsapp_settings', sa.Column('auto_renewal_grace_days', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_whatsapp_settings', 'auto_renewal_grace_days')
    op.drop_column('platform_whatsapp_settings', 'auto_renewal_enabled')
    op.drop_column('platform_whatsapp_settings', 'paystack_subaccount_code')
    op.drop_column('platform_whatsapp_settings', 'bank_swift_code')
    op.drop_column('platform_whatsapp_settings', 'bank_branch')
    op.drop_column('platform_whatsapp_settings', 'bank_name')
    op.drop_column('platform_whatsapp_settings', 'bank_account_number')
    op.drop_column('platform_whatsapp_settings', 'mpesa_account_name')
    op.drop_column('platform_whatsapp_settings', 'mpesa_till_number')
    op.drop_column('platform_whatsapp_settings', 'mpesa_paybill')
    op.drop_column('platform_whatsapp_settings', 'payment_method')
    op.drop_column('platform_whatsapp_settings', 'minimum_subscription_months')
    op.drop_constraint(op.f('fk_organizations_bypass_set_by_users'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'bypass_set_by')
    op.drop_column('organizations', 'bypass_reason')
    op.drop_column('organizations', 'licence_bypass')
    op.drop_column('organizations', 'grace_period_ends_at')
    op.drop_column('organizations', 'grace_period_days')
    # ### end Alembic commands ###
