"""Add provisioning models and tables

Revision ID: 51b3cf691430
Revises: aab6ee1906ab
Create Date: 2025-09-16 10:41:18.847703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b3cf691430'
down_revision = 'aab6ee1906ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
