"""Add timestamps to SupportTicket and TicketMessage models

Revision ID: 6df4d4bf3799
Revises: 092bd52af6a2
Create Date: 2026-01-27 19:14:50.142839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df4d4bf3799'
down_revision = '092bd52af6a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('support_tickets', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('ticket_messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ticket_messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_messages', 'updated_at')
    op.drop_column('ticket_messages', 'created_at')
    op.drop_column('support_tickets', 'updated_at')
    op.drop_column('support_tickets', 'created_at')
    # ### end Alembic commands ###
