"""Add licence management, package templates, SMS credit, and enhanced features

Revision ID: 99d8de282dcb
Revises: 51b3cf691430
Create Date: 2025-09-16 11:27:10.944324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d8de282dcb'
down_revision = '51b3cf691430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licence_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_core_feature', sa.Boolean(), nullable=False),
    sa.Column('requires_additional_payment', sa.Boolean(), nullable=False),
    sa.Column('additional_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('limit_type', sa.String(length=20), nullable=True),
    sa.Column('available_in_trial', sa.Boolean(), nullable=False),
    sa.Column('minimum_licence_type', sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', 'TRIAL', 'CUSTOM', name='licencetype'), nullable=False),
    sa.Column('configuration_schema', sa.JSON(), nullable=True),
    sa.Column('default_configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licence_features')),
    sa.UniqueConstraint('feature_code', name=op.f('uq_licence_features_feature_code'))
    )
    op.create_index(op.f('ix_licence_features_feature_name'), 'licence_features', ['feature_name'], unique=True)
    op.create_index(op.f('ix_licence_features_id'), 'licence_features', ['id'], unique=False)
    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_key', sa.String(length=100), nullable=False),
    sa.Column('licence_name', sa.String(length=100), nullable=False),
    sa.Column('licence_type', sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', 'TRIAL', 'CUSTOM', name='licencetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', 'CANCELLED', 'PENDING_RENEWAL', 'TRIAL', name='licencestatus'), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('last_renewal_date', sa.DateTime(), nullable=True),
    sa.Column('max_routers', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle_months', sa.Integer(), nullable=False),
    sa.Column('current_routers', sa.Integer(), nullable=False),
    sa.Column('current_users', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('auto_renewal_enabled', sa.Boolean(), nullable=False),
    sa.Column('renewal_reminder_days', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('licence_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licences'))
    )
    op.create_index(op.f('ix_licences_id'), 'licences', ['id'], unique=False)
    op.create_index(op.f('ix_licences_licence_key'), 'licences', ['licence_key'], unique=True)
    op.create_table('package_category_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('HOTSPOT', 'PPPOE', 'DATA_PLANS', 'FREE_TRIAL', 'PREMIUM', 'BUSINESS', 'STUDENT', 'PROMOTIONAL', name='packagecategory'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('default_billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('default_validity_days', sa.Integer(), nullable=False),
    sa.Column('supports_hotspot', sa.Boolean(), nullable=False),
    sa.Column('supports_pppoe', sa.Boolean(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggested_prices', sa.JSON(), nullable=True),
    sa.Column('default_features', sa.JSON(), nullable=True),
    sa.Column('required_features', sa.JSON(), nullable=True),
    sa.Column('optional_features', sa.JSON(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('show_in_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_category_configs')),
    sa.UniqueConstraint('category', name=op.f('uq_package_category_configs_category'))
    )
    op.create_index(op.f('ix_package_category_configs_id'), 'package_category_configs', ['id'], unique=False)
    op.create_table('bulk_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='bulkoperationstatus'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('successful_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('operation_data', sa.JSON(), nullable=False),
    sa.Column('results_data', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_item', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('can_retry', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bulk_operations_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_operations'))
    )
    op.create_index(op.f('ix_bulk_operations_id'), 'bulk_operations', ['id'], unique=False)
    op.create_index(op.f('ix_bulk_operations_operation_id'), 'bulk_operations', ['operation_id'], unique=True)
    op.create_table('licence_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_required', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_condition', sa.String(length=100), nullable=True),
    sa.Column('trigger_value', sa.String(length=50), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_licence_alerts_acknowledged_by_users')),
    sa.ForeignKeyConstraint(['licence_id'], ['licences.id'], name=op.f('fk_licence_alerts_licence_id_licences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licence_alerts'))
    )
    op.create_index(op.f('ix_licence_alerts_id'), 'licence_alerts', ['id'], unique=False)
    op.create_table('licence_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIAL', name='licencepaymentstatus'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('extends_licence_until', sa.DateTime(), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), nullable=False),
    sa.Column('is_upgrade', sa.Boolean(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['licences.id'], name=op.f('fk_licence_payments_licence_id_licences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licence_payments'))
    )
    op.create_index(op.f('ix_licence_payments_id'), 'licence_payments', ['id'], unique=False)
    op.create_index(op.f('ix_licence_payments_payment_reference'), 'licence_payments', ['payment_reference'], unique=True)
    op.create_table('licence_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence_id', sa.Integer(), nullable=False),
    sa.Column('routers_count', sa.Integer(), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('active_sessions', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('data_transferred_gb', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('daily_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sms_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('system_uptime_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_response_time_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('api_calls_count', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('log_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['licences.id'], name=op.f('fk_licence_usage_logs_licence_id_licences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licence_usage_logs')),
    sa.UniqueConstraint('licence_id', 'log_date', 'log_type', name='uq_licence_usage_log')
    )
    op.create_index(op.f('ix_licence_usage_logs_id'), 'licence_usage_logs', ['id'], unique=False)
    op.create_table('package_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('HOTSPOT', 'PPPOE', 'DATA_PLANS', 'FREE_TRIAL', 'PREMIUM', 'BUSINESS', 'STUDENT', 'PROMOTIONAL', name='packagecategory'), nullable=False),
    sa.Column('guide_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('parent_guide_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_package_guides_created_by_users')),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_package_guides_last_updated_by_users')),
    sa.ForeignKeyConstraint(['parent_guide_id'], ['package_guides.id'], name=op.f('fk_package_guides_parent_guide_id_package_guides')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_guides'))
    )
    op.create_index(op.f('ix_package_guides_id'), 'package_guides', ['id'], unique=False)
    op.create_table('package_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('HOTSPOT', 'PPPOE', 'DATA_PLANS', 'FREE_TRIAL', 'PREMIUM', 'BUSINESS', 'STUDENT', 'PROMOTIONAL', name='packagecategory'), nullable=False),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='packagetemplatestatus'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('price_template', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('download_speed', sa.Integer(), nullable=False),
    sa.Column('upload_speed', sa.Integer(), nullable=False),
    sa.Column('data_limit', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('configuration_template', sa.JSON(), nullable=True),
    sa.Column('features_template', sa.JSON(), nullable=True),
    sa.Column('restrictions_template', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_package_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_templates')),
    sa.UniqueConstraint('template_code', name=op.f('uq_package_templates_template_code'))
    )
    op.create_index(op.f('ix_package_templates_id'), 'package_templates', ['id'], unique=False)
    op.create_table('phone_number_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('formatted_number', sa.String(length=25), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_method', sa.String(length=20), nullable=True),
    sa.Column('validation_date', sa.DateTime(), nullable=True),
    sa.Column('validation_code', sa.String(length=10), nullable=True),
    sa.Column('validation_attempts', sa.Integer(), nullable=False),
    sa.Column('number_type', sa.String(length=20), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('associated_user_id', sa.Integer(), nullable=True),
    sa.Column('total_sms_sent', sa.Integer(), nullable=False),
    sa.Column('last_sms_sent', sa.DateTime(), nullable=True),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('delivery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('opt_in_marketing', sa.Boolean(), nullable=False),
    sa.Column('opt_in_notifications', sa.Boolean(), nullable=False),
    sa.Column('preferred_time_start', sa.String(length=5), nullable=False),
    sa.Column('preferred_time_end', sa.String(length=5), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('blacklist_reason', sa.String(length=200), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('blacklisted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['associated_user_id'], ['users.id'], name=op.f('fk_phone_number_management_associated_user_id_users')),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], name=op.f('fk_phone_number_management_blacklisted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_number_management'))
    )
    op.create_index(op.f('ix_phone_number_management_id'), 'phone_number_management', ['id'], unique=False)
    op.create_index(op.f('ix_phone_number_management_phone_number'), 'phone_number_management', ['phone_number'], unique=True)
    op.create_table('quick_setups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario', sa.String(length=100), nullable=False),
    sa.Column('packages_config', sa.JSON(), nullable=False),
    sa.Column('router_config', sa.JSON(), nullable=True),
    sa.Column('recommended_order', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('target_user_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quick_setups_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quick_setups'))
    )
    op.create_index(op.f('ix_quick_setups_id'), 'quick_setups', ['id'], unique=False)
    op.create_table('sms_credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.Enum('AFRICASTALKING', 'TWILIO', 'SMS_GLOBAL', 'CUSTOM', name='smsprovidertype'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('provider_account_id', sa.String(length=100), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('minimum_balance_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False),
    sa.Column('total_amount_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_cost_per_sms', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('auto_top_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_top_up_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('auto_top_up_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_config', sa.JSON(), nullable=True),
    sa.Column('api_credentials', sa.Text(), nullable=True),
    sa.Column('last_balance_check', sa.DateTime(), nullable=True),
    sa.Column('last_successful_send', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sms_credit_accounts_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_credit_accounts'))
    )
    op.create_index(op.f('ix_sms_credit_accounts_account_code'), 'sms_credit_accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_sms_credit_accounts_id'), 'sms_credit_accounts', ['id'], unique=False)
    op.create_table('package_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('assignment_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_create_users', sa.Boolean(), nullable=False),
    sa.Column('custom_configuration', sa.JSON(), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('speed_override', sa.JSON(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=False),
    sa.Column('last_sync_date', sa.DateTime(), nullable=True),
    sa.Column('users_created', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_package_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['plan_id'], ['service_plans.id'], name=op.f('fk_package_assignments_plan_id_service_plans')),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], name=op.f('fk_package_assignments_router_id_routers')),
    sa.ForeignKeyConstraint(['template_id'], ['package_templates.id'], name=op.f('fk_package_assignments_template_id_package_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_assignments'))
    )
    op.create_index(op.f('ix_package_assignments_id'), 'package_assignments', ['id'], unique=False)
    op.create_table('package_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('use_case', sa.String(length=100), nullable=True),
    sa.Column('router_model', sa.String(length=50), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], name=op.f('fk_package_ratings_moderated_by_users')),
    sa.ForeignKeyConstraint(['template_id'], ['package_templates.id'], name=op.f('fk_package_ratings_template_id_package_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_package_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_ratings')),
    sa.UniqueConstraint('template_id', 'user_id', name='uq_template_user_rating')
    )
    op.create_index(op.f('ix_package_ratings_id'), 'package_ratings', ['id'], unique=False)
    op.create_table('sms_credit_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_required', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trigger_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sms_credit_accounts.id'], name=op.f('fk_sms_credit_alerts_account_id_sms_credit_accounts')),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_sms_credit_alerts_acknowledged_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_credit_alerts'))
    )
    op.create_index(op.f('ix_sms_credit_alerts_id'), 'sms_credit_alerts', ['id'], unique=False)
    op.create_table('sms_credit_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stats_date', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_delivered', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_cost_per_sms', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('delivery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_delivery_time_seconds', sa.Integer(), nullable=False),
    sa.Column('notification_sms', sa.Integer(), nullable=False),
    sa.Column('marketing_sms', sa.Integer(), nullable=False),
    sa.Column('verification_sms', sa.Integer(), nullable=False),
    sa.Column('alert_sms', sa.Integer(), nullable=False),
    sa.Column('top_ups_count', sa.Integer(), nullable=False),
    sa.Column('top_ups_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lowest_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('highest_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sms_credit_accounts.id'], name=op.f('fk_sms_credit_usage_stats_account_id_sms_credit_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_credit_usage_stats')),
    sa.UniqueConstraint('account_id', 'stats_date', 'period_type', name='uq_sms_stats_account_date')
    )
    op.create_index(op.f('ix_sms_credit_usage_stats_id'), 'sms_credit_usage_stats', ['id'], unique=False)
    op.create_table('sms_top_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_up_reference', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sms_credits', sa.Integer(), nullable=False),
    sa.Column('cost_per_sms', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', name='smstransactionstatus'), nullable=False),
    sa.Column('is_auto_top_up', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sms_credit_accounts.id'], name=op.f('fk_sms_top_ups_account_id_sms_credit_accounts')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_sms_top_ups_approved_by_users')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_sms_top_ups_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_top_ups'))
    )
    op.create_index(op.f('ix_sms_top_ups_id'), 'sms_top_ups', ['id'], unique=False)
    op.create_index(op.f('ix_sms_top_ups_top_up_reference'), 'sms_top_ups', ['top_up_reference'], unique=True)
    op.create_table('sms_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('TOP_UP', 'USAGE', 'REFUND', 'ADJUSTMENT', 'BONUS', name='smstransactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', name='smstransactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('sms_count', sa.Integer(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('top_up_id', sa.Integer(), nullable=True),
    sa.Column('balance_before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sms_credit_accounts.id'], name=op.f('fk_sms_transactions_account_id_sms_credit_accounts')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_sms_transactions_notification_id_notifications')),
    sa.ForeignKeyConstraint(['top_up_id'], ['sms_top_ups.id'], name=op.f('fk_sms_transactions_top_up_id_sms_top_ups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sms_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_transactions'))
    )
    op.create_index(op.f('ix_sms_transactions_id'), 'sms_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_sms_transactions_transaction_id'), 'sms_transactions', ['transaction_id'], unique=True)
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_key'), table_name='configurations')
    op.drop_table('configurations')
    op.add_column('notification_templates', sa.Column('html_template', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('user_type_specific', sa.Boolean(), nullable=False))
    op.add_column('notification_templates', sa.Column('hotspot_template', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('pppoe_template', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('supports_html', sa.Boolean(), nullable=False))
    op.add_column('notification_templates', sa.Column('supports_markdown', sa.Boolean(), nullable=False))
    op.add_column('notification_templates', sa.Column('css_styles', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notification_templates', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('notification_templates', sa.Column('version', sa.String(length=20), nullable=False))
    op.add_column('notification_templates', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.add_column('notification_templates', sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('notification_templates', sa.Column('last_tested', sa.DateTime(), nullable=True))
    op.add_column('notification_templates', sa.Column('test_results', sa.Text(), nullable=True))
    op.add_column('notification_templates', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('notification_templates', sa.Column('last_updated_by', sa.Integer(), nullable=True))
    op.add_column('notification_templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notification_templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(op.f('fk_notification_templates_last_updated_by_users'), 'notification_templates', 'users', ['last_updated_by'], ['id'])
    op.create_foreign_key(op.f('fk_notification_templates_created_by_users'), 'notification_templates', 'users', ['created_by'], ['id'])
    op.add_column('payments', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('disbursement_method', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('disbursement_reference', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('is_manual_payment', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('recorded_by', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('receipt_image_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(op.f('fk_payments_recorded_by_users'), 'payments', 'users', ['recorded_by'], ['id'])
    op.create_foreign_key(op.f('fk_payments_verified_by_users'), 'payments', 'users', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payments_verified_by_users'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_recorded_by_users'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'receipt_image_url')
    op.drop_column('payments', 'recorded_by')
    op.drop_column('payments', 'is_manual_payment')
    op.drop_column('payments', 'disbursement_reference')
    op.drop_column('payments', 'disbursement_method')
    op.drop_column('payments', 'verification_notes')
    op.drop_column('payments', 'verified_at')
    op.drop_column('payments', 'verified_by')
    op.drop_constraint(op.f('fk_notification_templates_created_by_users'), 'notification_templates', type_='foreignkey')
    op.drop_constraint(op.f('fk_notification_templates_last_updated_by_users'), 'notification_templates', type_='foreignkey')
    op.drop_column('notification_templates', 'updated_at')
    op.drop_column('notification_templates', 'created_at')
    op.drop_column('notification_templates', 'last_updated_by')
    op.drop_column('notification_templates', 'created_by')
    op.drop_column('notification_templates', 'test_results')
    op.drop_column('notification_templates', 'last_tested')
    op.drop_column('notification_templates', 'success_rate')
    op.drop_column('notification_templates', 'usage_count')
    op.drop_column('notification_templates', 'version')
    op.drop_column('notification_templates', 'tags')
    op.drop_column('notification_templates', 'category')
    op.drop_column('notification_templates', 'css_styles')
    op.drop_column('notification_templates', 'supports_markdown')
    op.drop_column('notification_templates', 'supports_html')
    op.drop_column('notification_templates', 'pppoe_template')
    op.drop_column('notification_templates', 'hotspot_template')
    op.drop_column('notification_templates', 'user_type_specific')
    op.drop_column('notification_templates', 'html_template')
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_type', postgresql.ENUM('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'ENCRYPTED', name='configtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    op.create_index(op.f('ix_configurations_key'), 'configurations', ['key'], unique=True)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    op.drop_index(op.f('ix_sms_transactions_transaction_id'), table_name='sms_transactions')
    op.drop_index(op.f('ix_sms_transactions_id'), table_name='sms_transactions')
    op.drop_table('sms_transactions')
    op.drop_index(op.f('ix_sms_top_ups_top_up_reference'), table_name='sms_top_ups')
    op.drop_index(op.f('ix_sms_top_ups_id'), table_name='sms_top_ups')
    op.drop_table('sms_top_ups')
    op.drop_index(op.f('ix_sms_credit_usage_stats_id'), table_name='sms_credit_usage_stats')
    op.drop_table('sms_credit_usage_stats')
    op.drop_index(op.f('ix_sms_credit_alerts_id'), table_name='sms_credit_alerts')
    op.drop_table('sms_credit_alerts')
    op.drop_index(op.f('ix_package_ratings_id'), table_name='package_ratings')
    op.drop_table('package_ratings')
    op.drop_index(op.f('ix_package_assignments_id'), table_name='package_assignments')
    op.drop_table('package_assignments')
    op.drop_index(op.f('ix_sms_credit_accounts_id'), table_name='sms_credit_accounts')
    op.drop_index(op.f('ix_sms_credit_accounts_account_code'), table_name='sms_credit_accounts')
    op.drop_table('sms_credit_accounts')
    op.drop_index(op.f('ix_quick_setups_id'), table_name='quick_setups')
    op.drop_table('quick_setups')
    op.drop_index(op.f('ix_phone_number_management_phone_number'), table_name='phone_number_management')
    op.drop_index(op.f('ix_phone_number_management_id'), table_name='phone_number_management')
    op.drop_table('phone_number_management')
    op.drop_index(op.f('ix_package_templates_id'), table_name='package_templates')
    op.drop_table('package_templates')
    op.drop_index(op.f('ix_package_guides_id'), table_name='package_guides')
    op.drop_table('package_guides')
    op.drop_index(op.f('ix_licence_usage_logs_id'), table_name='licence_usage_logs')
    op.drop_table('licence_usage_logs')
    op.drop_index(op.f('ix_licence_payments_payment_reference'), table_name='licence_payments')
    op.drop_index(op.f('ix_licence_payments_id'), table_name='licence_payments')
    op.drop_table('licence_payments')
    op.drop_index(op.f('ix_licence_alerts_id'), table_name='licence_alerts')
    op.drop_table('licence_alerts')
    op.drop_index(op.f('ix_bulk_operations_operation_id'), table_name='bulk_operations')
    op.drop_index(op.f('ix_bulk_operations_id'), table_name='bulk_operations')
    op.drop_table('bulk_operations')
    op.drop_index(op.f('ix_package_category_configs_id'), table_name='package_category_configs')
    op.drop_table('package_category_configs')
    op.drop_index(op.f('ix_licences_licence_key'), table_name='licences')
    op.drop_index(op.f('ix_licences_id'), table_name='licences')
    op.drop_table('licences')
    op.drop_index(op.f('ix_licence_features_id'), table_name='licence_features')
    op.drop_index(op.f('ix_licence_features_feature_name'), table_name='licence_features')
    op.drop_table('licence_features')
    # ### end Alembic commands ###
