"""Add provisioning models and tables

Revision ID: aab6ee1906ab
Revises: 
Create Date: 2025-09-16 10:39:36.211430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aab6ee1906ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='provisioningstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('CONNECTION', 'CONFIGURATION', 'SERVICE_SETUP', name='provisioningstep'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('service_type', sa.Enum('PPPOE_SERVER', 'HOTSPOT', 'BOTH', 'BRIDGE', name='servicetype'), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='provisioningpriority'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_required', sa.Boolean(), nullable=False),
    sa.Column('rollback_completed', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], name=op.f('fk_provisioning_sessions_router_id_routers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provisioning_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisioning_sessions'))
    )
    op.create_index(op.f('ix_provisioning_sessions_id'), 'provisioning_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_provisioning_sessions_session_id'), 'provisioning_sessions', ['session_id'], unique=True)
    op.create_table('provisioning_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('service_type', sa.Enum('PPPOE_SERVER', 'HOTSPOT', 'BOTH', 'BRIDGE', name='servicetype'), nullable=False),
    sa.Column('router_model', sa.String(length=50), nullable=True),
    sa.Column('min_routeros_version', sa.String(length=20), nullable=True),
    sa.Column('configuration_schema', sa.JSON(), nullable=False),
    sa.Column('default_configuration', sa.JSON(), nullable=False),
    sa.Column('command_templates', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_provisioning_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisioning_templates')),
    sa.UniqueConstraint('name', 'version', name='uq_template_name_version')
    )
    op.create_index(op.f('ix_provisioning_templates_id'), 'provisioning_templates', ['id'], unique=False)
    op.create_table('provisioning_step_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('CONNECTION', 'CONFIGURATION', 'SERVICE_SETUP', name='provisioningstep'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='provisioningstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('sub_steps_total', sa.Integer(), nullable=False),
    sa.Column('sub_steps_completed', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['provisioning_sessions.id'], name=op.f('fk_provisioning_step_logs_session_id_provisioning_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisioning_step_logs'))
    )
    op.create_index(op.f('ix_provisioning_step_logs_id'), 'provisioning_step_logs', ['id'], unique=False)
    op.create_table('router_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('configuration_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_name', sa.String(length=100), nullable=True),
    sa.Column('configuration_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_backup', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], name=op.f('fk_router_configurations_applied_by_users')),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], name=op.f('fk_router_configurations_router_id_routers')),
    sa.ForeignKeyConstraint(['session_id'], ['provisioning_sessions.id'], name=op.f('fk_router_configurations_session_id_provisioning_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_router_configurations'))
    )
    op.create_index(op.f('ix_router_configurations_id'), 'router_configurations', ['id'], unique=False)
    op.create_table('provisioning_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('step_log_id', sa.Integer(), nullable=True),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='provisioningstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rollback_command', sa.Text(), nullable=True),
    sa.Column('rollback_executed', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['provisioning_sessions.id'], name=op.f('fk_provisioning_commands_session_id_provisioning_sessions')),
    sa.ForeignKeyConstraint(['step_log_id'], ['provisioning_step_logs.id'], name=op.f('fk_provisioning_commands_step_log_id_provisioning_step_logs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisioning_commands'))
    )
    op.create_index(op.f('ix_provisioning_commands_id'), 'provisioning_commands', ['id'], unique=False)
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_key'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_column('billing_cycles', 'created_at')
    op.drop_column('billing_cycles', 'updated_at')
    op.drop_column('notification_templates', 'created_at')
    op.drop_column('notification_templates', 'updated_at')
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.create_foreign_key(op.f('fk_plan_features_plan_id_service_plans'), 'plan_features', 'service_plans', ['plan_id'], ['id'])
    op.drop_column('plan_features', 'created_at')
    op.drop_column('plan_features', 'updated_at')
    op.create_foreign_key(op.f('fk_plan_pricing_plan_id_service_plans'), 'plan_pricing', 'service_plans', ['plan_id'], ['id'])
    op.drop_column('plan_pricing', 'created_at')
    op.drop_column('plan_pricing', 'updated_at')
    op.drop_column('subscription_history', 'created_at')
    op.drop_column('subscription_history', 'updated_at')
    op.drop_column('subscription_usage_logs', 'created_at')
    op.drop_column('subscription_usage_logs', 'updated_at')
    op.drop_column('support_tickets', 'created_at')
    op.drop_column('support_tickets', 'updated_at')
    op.drop_column('ticket_messages', 'created_at')
    op.drop_column('ticket_messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_messages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('ticket_messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('support_tickets', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscription_usage_logs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscription_usage_logs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscription_history', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('subscription_history', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('plan_pricing', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('plan_pricing', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_plan_pricing_plan_id_service_plans'), 'plan_pricing', type_='foreignkey')
    op.add_column('plan_features', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('plan_features', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_plan_features_plan_id_service_plans'), 'plan_features', type_='foreignkey')
    op.add_column('notifications', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('notification_templates', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('notification_templates', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('billing_cycles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('billing_cycles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_table('configurations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config_type', postgresql.ENUM('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'ENCRYPTED', name='configtype'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_encrypted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_sensitive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations'))
    )
    op.create_index(op.f('ix_configurations_key'), 'configurations', ['key'], unique=True)
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    op.drop_index(op.f('ix_provisioning_commands_id'), table_name='provisioning_commands')
    op.drop_table('provisioning_commands')
    op.drop_index(op.f('ix_router_configurations_id'), table_name='router_configurations')
    op.drop_table('router_configurations')
    op.drop_index(op.f('ix_provisioning_step_logs_id'), table_name='provisioning_step_logs')
    op.drop_table('provisioning_step_logs')
    op.drop_index(op.f('ix_provisioning_templates_id'), table_name='provisioning_templates')
    op.drop_table('provisioning_templates')
    op.drop_index(op.f('ix_provisioning_sessions_session_id'), table_name='provisioning_sessions')
    op.drop_index(op.f('ix_provisioning_sessions_id'), table_name='provisioning_sessions')
    op.drop_table('provisioning_sessions')
    # ### end Alembic commands ###
