"""
Bootstrap endpoints for MikroTik device provisioning.
Handles initial device connection and script generation.
"""
import logging
from fastapi import APIRouter, Depends, Query, HTTPException, Request
from fastapi.responses import PlainTextResponse
from app.models.user import User
from app.api.deps import require_technician_or_admin

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/command")
async def get_bootstrap_command(
    request: Request,
    identity: str = Query("MikroTik"),
    api_port: int = Query(8728),
    interface: str = Query("ether2"),
    current_user: User = Depends(require_technician_or_admin()),
):
    """Generate a one-liner RouterOS command for initial device provisioning with proper access token.
    
    This command downloads and executes the bootstrap script from the current domain.
    The script enables API access and sets basic device configuration.
    """
    try:
        # Get the current domain from the request
        base = f"{request.url.scheme}://{request.url.netloc}"
        
        # Generate provisioning token for this specific router
        from app.services.auth_service import AuthService
        from app.core.database import get_db
        
        db = next(get_db())
        auth_service = AuthService(db)
        
        # Create provisioning token with limited permissions
        provisioning_token = auth_service.create_provisioning_token(
            user_id=current_user.id,
            router_id=0,  # Will be updated when router is created
            permissions=["provisioning.execute", "router.configure"]
        )
        
        # Generate the command with token similar to Centipid's approach
        script_url = f"{base}/api/v1/provisioning/bootstrap/script?token={provisioning_token}&identity={identity}&api_port={api_port}&interface={interface}"
        command = f"/tool fetch mode=https url=\"{script_url}\" dst-path=codevertex.rsc; delay 2s; import codevertex.rsc;"
        
        notes = [
            "If device mode is not allowed, run: /system/device-mode update mode=advanced",
            "Ensure the device has internet access to fetch the script",
            "The delay ensures the file is fully downloaded before import",
            "The token provides secure access to the provisioning script",
        ]
        
        return {
            "command": command, 
            "script_url": script_url, 
            "token": provisioning_token,
            "expires_in": 3600,  # 1 hour
            "notes": notes
        }
    
    except Exception as e:
        logger.error(f"Failed to generate bootstrap command: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate bootstrap command")


@router.get("/script", response_class=PlainTextResponse)
async def get_bootstrap_script(
    request: Request,
    token: str = Query(...),
    identity: str = Query("MikroTik"),
    api_port: int = Query(8728),
    interface: str = Query("ether2"),
):
    """Return a minimal RouterOS script for first-touch provisioning with token verification.

    This enables API on the specified port, sets identity, and ensures the interface exists.
    The advanced configuration is later handled by the provisioning workflow.
    """
    try:
        # Verify provisioning token
        from app.services.auth_service import AuthService
        from app.core.database import get_db
        
        db = next(get_db())
        auth_service = AuthService(db)
        
        token_data = auth_service.verify_provisioning_token(token)
        if not token_data:
            raise HTTPException(status_code=401, detail="Invalid provisioning token")
        
        # Log the provisioning attempt
        logger.info(f"Provisioning script requested by user {token_data['sub']} for router {token_data.get('router_id', 'pending')}")
        
        lines = [
            "; Codevertex bootstrap script - Initial device setup",
            "; Generated by Codevertex ISP Billing System",
            f"; User ID: {token_data['sub']}",
            f"; Permissions: {', '.join(token_data.get('permissions', []))}",
            "",
            f"/system/identity/set name={identity}",
            f"/ip/service/set api disabled=no port={api_port}",
            "",
            "; Optional: allow Winbox & SSH hardened",
            "/ip/service/set winbox disabled=no",
            "/ip/service/set ssh port=2222",
            "",
            "; Ensure interface exists (no-op if not)",
            f"/interface/print where name={interface}",
            "",
            "; Log successful bootstrap",
            f":log info message=\"Codevertex bootstrap completed for {identity}\"",
            f":log info message=\"Provisioning token verified for user {token_data['sub']}\"",
        ]
        
        return "\n".join(lines) + "\n"
    
    except Exception as e:
        logger.error(f"Failed to generate bootstrap script: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate bootstrap script")


@router.get("/complete", response_class=PlainTextResponse)
async def get_complete_script(
    current_user: User = Depends(require_technician_or_admin()),
):
    """Return the complete RouterOS configuration script.
    
    This is the comprehensive script that configures all services
    after the initial bootstrap is complete.
    """
    try:
        script_content = """
; Codevertex Complete Configuration Script
; This script configures all services after bootstrap

; System logging
/system logging add topics=info action=memory
/system logging add topics=error action=memory

; Bridge configuration
/interface bridge add name=codevertex-bridge protocol-mode=none
/interface bridge port add bridge=codevertex-bridge interface=ether2
/interface bridge port add bridge=codevertex-bridge interface=ether3
/interface bridge port add bridge=codevertex-bridge interface=ether4
/interface bridge port add bridge=codevertex-bridge interface=ether5
/interface bridge port add bridge=codevertex-bridge interface=ether6
/interface bridge port add bridge=codevertex-bridge interface=ether7
/interface bridge port add bridge=codevertex-bridge interface=ether8

; IP configuration
/ip address add address=192.168.88.1/24 interface=codevertex-bridge

; DHCP Server
/ip dhcp-server add interface=codevertex-bridge address-pool=codevertex-pool disabled=no
/ip dhcp-server network add address=192.168.88.0/24 gateway=192.168.88.1 dns-server=8.8.8.8,8.8.4.4
/ip pool add name=codevertex-pool ranges=192.168.88.100-192.168.88.200

; DNS configuration
/ip dns set servers=8.8.8.8,8.8.4.4 allow-remote-requests=yes

; Hotspot configuration
/ip hotspot setup add name=codevertex-hotspot interface=codevertex-bridge address-pool=codevertex-pool profile=codevertex-profile
/ip hotspot profile add name=codevertex-profile use-radius=no
/ip hotspot ip-binding add address=192.168.88.1 to-address=192.168.88.1 type=bypassed

; PPPoE Server configuration
/interface pppoe-server server add interface=codevertex-bridge service-name=codevertex-pppoe authentication=pap,chap,mschap1,mschap2
/ppp profile add name=codevertex-pppoe local-address=192.168.88.1 remote-address=codevertex-pppoe-pool

; Firewall rules
/ip firewall filter add chain=input action=accept connection-state=established,related
/ip firewall filter add chain=input action=accept src-address=192.168.88.0/24
/ip firewall filter add chain=input action=drop

; NAT configuration
/ip firewall nat add chain=srcnat action=masquerade out-interface=ether1

; Anti-sharing rules (TTL modification)
/ip firewall mangle add chain=forward action=change-ttl new-ttl=64 ttl=65 protocol=tcp dst-port=80,443,53,21,22,23,25,110,143,993,995,8080,8443
/ip firewall mangle add chain=forward action=change-ttl new-ttl=64 ttl=65 protocol=udp dst-port=53,67,68,123,161,162,500,4500

; Queue tree for bandwidth management
/queue tree add name=codevertex-main parent=global max-limit=100M
/queue tree add name=codevertex-hotspot parent=codevertex-main max-limit=50M

; System configuration
/system clock set time-zone-name=UTC
/system ntp client set enabled=yes primary-ntp=pool.ntp.org

; Final system message
:log info message="Codevertex ISP Billing System - Router configured successfully"
"""
        
        return script_content
    
    except Exception as e:
        logger.error(f"Failed to generate complete script: {e}")
        raise HTTPException(status_code=500, detail="Failed to generate complete script")
